// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCBzyxlUgkbc27wAQJgzN8SDnZ5rHh9c-k',
//     appId: '1:475520330114:web:43c726daab4cadde22479b',
//     messagingSenderId: '475520330114',
//     projectId: 'synq-46db1',
//     authDomain: 'synq-46db1.firebaseapp.com',
//     storageBucket: 'synq-46db1.firebasestorage.app',
//     measurementId: 'G-42MRY83SGY',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyA3S1Vtub3YjZO5kftaCL_4TmvVuqAHE5U',
//     appId: '1:475520330114:android:2b4797f0e3c4c62122479b',
//     messagingSenderId: '475520330114',
//     projectId: 'synq-46db1',
//     storageBucket: 'synq-46db1.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBq4qN7CTClBxFS5tKhSiwIixbrNhigNLU',
//     appId: '1:475520330114:ios:15eb2f0db4cc3cd622479b',
//     messagingSenderId: '475520330114',
//     projectId: 'synq-46db1',
//     storageBucket: 'synq-46db1.firebasestorage.app',
//     iosClientId: '475520330114-e3f3i0ktpvv3ke1robed4gbv1ldgtb77.apps.googleusercontent.com',
//     iosBundleId: 'com.ak.synq',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBq4qN7CTClBxFS5tKhSiwIixbrNhigNLU',
//     appId: '1:475520330114:ios:15eb2f0db4cc3cd622479b',
//     messagingSenderId: '475520330114',
//     projectId: 'synq-46db1',
//     storageBucket: 'synq-46db1.firebasestorage.app',
//     iosClientId: '475520330114-e3f3i0ktpvv3ke1robed4gbv1ldgtb77.apps.googleusercontent.com',
//     iosBundleId: 'com.ak.synq',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCBzyxlUgkbc27wAQJgzN8SDnZ5rHh9c-k',
//     appId: '1:475520330114:web:f29d086c4820d5af22479b',
//     messagingSenderId: '475520330114',
//     projectId: 'synq-46db1',
//     authDomain: 'synq-46db1.firebaseapp.com',
//     storageBucket: 'synq-46db1.firebasestorage.app',
//     measurementId: 'G-N3MP6G60CC',
//   );

// }